baseURL = "https://bhrg3se.github.io/mysite/"
languageCode = "en-us"
title = "Bhargab"
theme = "hugo-theme-nix"

[params]
    Name = "Bhargab"
    HeaderUsername = "bhrg3se"
    HeaderHostname = "bhargab.com.np"
    About = "Hi, I am Bhargab. I am a software engineer."
    ProfilePicture = "avatar.png"
    GithubID = "bhrg3se"
    GitlabId = "bhrg3se"
    LinkedInID = "bhrg3se"
    SpotifyID = "21pwcw5otjkx4otck6nrb3nra"
    TelegramID = "bhrg3se"
    TwitterID = "bhrg3se"
    InstagramID = "mehawwwww"

